backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://kartikshots.netlify.com

media_folder: content/projects
public_folder: content/projects

collections:
  - name: 'color' # Used in routes, e.g., /admin/collections/blog
    label: 'Color' # Used in the UI
    folder: 'content/projects' # The path to the folder where the documents are stored
    media_folder: 'color'
    public_folder: 'color'
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }

  - name: 'extreme-neon' # Used in routes, e.g., /admin/collections/blog
    label: 'Extreme Neon' # Used in the UI
    folder: 'content/projects' # The path to the folder where the documents are stored
    media_folder: 'neon'
    public_folder: 'neon'
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }

  - name: 'black-and-white' # Used in routes, e.g., /admin/collections/blog
    label: 'Black and White' # Used in the UI
    folder: 'content/projects' # The path to the folder where the documents are stored
    media_folder: 'bw'
    public_folder: 'bw'
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }

  - name: 'breakfast' # Used in routes, e.g., /admin/collections/blog
    label: 'Breakfast' # Used in the UI
    folder: 'content/projects' # The path to the folder where the documents are stored
    media_folder: 'breakfast'
    public_folder: 'breakfast'
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
